apiVersion: krateo.io/v1alpha1
kind: Template
metadata:
  name: Dummy App
  annotations:
    title: Dummy App
    description: Dummy App Template
    icon: fa-solid fa-plane-departure
    owner: mauro.sala@kiratech.it
  labels:
    tags:
      - dummy app
      - template
      - krateo
spec:
  widgets:
    - title: Name and description
      description: Name your app
      properties:
        name:
          title: Name
          description: Unique name of the component
          required: true
