# {{=<% %>=}}
spring:
  application:
    name: <% name %>
  mvc:
    view:
      suffix: .html
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: postgres
    password: secretpassword
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2

liquibase:
  enabled: true
  user: liquibase
  password: password
  change-log: classpath:db/changelog/liquibase-changeLog.xml
